import type { Metadata } from 'next';
import Providers from './providers/providers';
import './globals.css';
import Header from './components/Header';
import { Inter } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen bg-neutral-950 text-neutral-100 antialiased`}
      >
        <Providers>
          <Header />
          <main className=" mx-auto max-w-7xl px-4 py-6">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
